SELECT
    COLUMN_NAME,
    COLUMN_TYPE,
    COLLATION_NAME,
    IS_NULLABLE,
    COLUMN_KEY,
    COLUMN_DEFAULT,
    EXTRA,
    PRIVILEGES,
    COLUMN_COMMENT
    DATA_TYPE,
    UPPER(
    CASE
    WHEN UPPER( DATA_TYPE )= 'TINYINT' THEN
    CASE
    WHEN LOCATE('ZEROFILL',UPPER( COLUMN_TYPE )) = 0 AND LOCATE('UNSIGNED',UPPER( COLUMN_TYPE )) = 0 AND LOCATE( '(1)', COLUMN_TYPE ) != 0 THEN 'BIT'
    WHEN LOCATE('UNSIGNED',UPPER( COLUMN_TYPE )) != 0 AND LOCATE('UNSIGNED',UPPER( DATA_TYPE )) = 0 THEN 'TINYINT UNSIGNED'
    ELSE DATA_TYPE
    END
    WHEN LOCATE('UNSIGNED',UPPER( COLUMN_TYPE )) != 0 AND LOCATE('UNSIGNED',UPPER( DATA_TYPE )) = 0 AND LOCATE('SET',UPPER( DATA_TYPE )) <> 1 AND LOCATE('ENUM',UPPER( DATA_TYPE )) <> 1 THEN CONCAT( DATA_TYPE, ' UNSIGNED' )
    WHEN UPPER( DATA_TYPE )= 'POINT' THEN 'GEOMETRY'
    WHEN UPPER( DATA_TYPE )= 'LINESTRING' THEN 'GEOMETRY'
    WHEN UPPER( DATA_TYPE )= 'POLYGON' THEN 'GEOMETRY'
    WHEN UPPER( DATA_TYPE )= 'MULTIPOINT' THEN 'GEOMETRY'
    WHEN UPPER( DATA_TYPE )= 'MULTILINESTRING' THEN 'GEOMETRY'
    WHEN UPPER( DATA_TYPE )= 'MULTIPOLYGON' THEN 'GEOMETRY'
    WHEN UPPER( DATA_TYPE )= 'GEOMETRYCOLLECTION' THEN 'GEOMETRY'
    WHEN UPPER( DATA_TYPE )= 'GEOMCOLLECTION' THEN 'GEOMETRY'
    WHEN UPPER( DATA_TYPE )= 'INT' THEN 'INTEGER'
    WHEN UPPER( DATA_TYPE )= 'DATETIME' THEN 'DATE'
    WHEN UPPER( DATA_TYPE )= 'LONGTEXT' THEN 'LONGVARCHAR'
    WHEN UPPER( DATA_TYPE )= 'MEDIUMTEXT' THEN 'VARCHAR'
    ELSE UPPER( DATA_TYPE )
    END
    ) AS TYPE_NAME
FROM
    INFORMATION_SCHEMA.COLUMNS
WHERE
    TABLE_SCHEMA = '%s' and TABLE_NAME = '%s'
ORDER BY
    TABLE_SCHEMA,TABLE_NAME,ORDINAL_POSITION